# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Farlow Designs
email: tyler@farlowdesigns.com
description: > # this means to ignore newlines until "baseurl:"
  Farlow Designs is a one stop shop for all of your web and digital media needs. We offer web design, logo design and branding, search engine optomization, videography, photography, and animation services.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://farlowdesigns.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

